# Site settings
title: Paul Messina
twitter_username: paulrmessina
name: Paul Messina

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Website
   url: http://paulm.com.ar/
 - title: GitHub
   url: https://github.com/paulrm
 - title: StackOverflow
   url: http://stackoverflow.com/users/2201186/paulrm
 - title: LinkedIn
   url: https://www.linkedin.com/in/paulrmessina

